'use client';

import { useEffect, useRef } from 'react';

/**
 * Giscus comment widget. Stores comments in GitHub Discussions on Connor's repo.
 * Configured via env vars (see setup checklist in README):
 *   NEXT_PUBLIC_GISCUS_REPO         = "connor/quantum-ledger"
 *   NEXT_PUBLIC_GISCUS_REPO_ID      = generated by giscus.app
 *   NEXT_PUBLIC_GISCUS_CATEGORY     = "Discussions"
 *   NEXT_PUBLIC_GISCUS_CATEGORY_ID  = generated by giscus.app
 *
 * Falls back to a "coming soon" hint when unset so the page still renders.
 */
export function Giscus({ mapping = 'pathname' }: { mapping?: 'pathname' | 'title' | 'og:title' }) {
  const ref = useRef<HTMLDivElement>(null);

  const repo = process.env.NEXT_PUBLIC_GISCUS_REPO;
  const repoId = process.env.NEXT_PUBLIC_GISCUS_REPO_ID;
  const category = process.env.NEXT_PUBLIC_GISCUS_CATEGORY ?? 'General';
  const categoryId = process.env.NEXT_PUBLIC_GISCUS_CATEGORY_ID;

  useEffect(() => {
    if (!ref.current || !repo || !repoId || !categoryId) return;
    if (ref.current.querySelector('script[src*="giscus"]')) return;

    const script = document.createElement('script');
    script.src = 'https://giscus.app/client.js';
    script.async = true;
    script.crossOrigin = 'anonymous';
    script.setAttribute('data-repo', repo);
    script.setAttribute('data-repo-id', repoId);
    script.setAttribute('data-category', category);
    script.setAttribute('data-category-id', categoryId);
    script.setAttribute('data-mapping', mapping);
    script.setAttribute('data-strict', '0');
    script.setAttribute('data-reactions-enabled', '1');
    script.setAttribute('data-emit-metadata', '0');
    script.setAttribute('data-input-position', 'top');
    script.setAttribute('data-theme', 'dark_dimmed');
    script.setAttribute('data-lang', 'en');
    ref.current.appendChild(script);

    return () => {
      if (ref.current) ref.current.innerHTML = '';
    };
  }, [repo, repoId, category, categoryId, mapping]);

  if (!repo || !repoId || !categoryId) {
    return (
      <div className="not-prose my-10 card p-6 border-dashed">
        <p className="eyebrow mb-2">Discussion</p>
        <p className="text-text-secondary text-sm leading-relaxed">
          Comments will appear here once we wire up GitHub Discussions. In the meantime, the live
          conversation is on Discord — join via the{' '}
          <a href="/community" className="text-accent-quantum hover:underline">community page</a>.
        </p>
      </div>
    );
  }

  return (
    <section className="not-prose my-12">
      <h3 className="eyebrow mb-4">Discuss this</h3>
      <div ref={ref} className="giscus-container" />
    </section>
  );
}
